### ISSUE TITLE
Stream rate goes to 0Kb/s and image is not updated anymore

### ISSUE THREAD

**Issue by Rai-Rai** [kamermans/wyze-mjpeg-proxy#1]
Hi, every x weeks I don't get updated mjpegs anymore, the container reports in the logs happily "Stream rate for xxxx: 0.00 KB/s.
Recovers only by restarting the container

I have two cameras connected, One camera source is routed via synology Surveillanace station and the other one directly connects to a camera. happens for both of them.

Config:
```
verbosity: 1
port: 8190
streams:
  - name: gartentor
    source: rtsp://USER:PW@192.168.0.99:554/Sms=3.unicast
    resolution: 1280x720
    quality: 100
    framerate: 1
  - name: gartentor2
    source: rtsp://USER:PW@192.168.0.55:554/stream1
    resolution: 1280x720
    quality: 100
    framerate: 1
```

![Image](https://github.com/user-attachments/assets/227eaaf8-3794-4cfc-bb90-808d8df206f3)

Any idea?
Reconnecting to the source if the frame rate gets downt to 0.00Kb could already solve this issue.
